name: Test Merge

on:
  pull_request:
    types: [closed] 

jobs:

  build:
    if: github.event.pull_request.merged == true
    name: Testing
    runs-on: ubuntu-latest
    steps:

    - name: Step 1
      run: |
        echo " Step 1"

    - name: Step 2
      run: |
        echo " Step 2"
