name: Go Merge

on:
  - push
  # pull_request:
  #   types: [closed] 


jobs:

  build:
    # if: github.event.pull_request.merged == true
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.14
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        go get -v -t -d ./...

    - name: Build
      run: go build -v -o app .

    - name: Test
      run: go test -v .

    - name: Install jx-release-version
      run: |
        wget https://github.com/jenkins-x/jx-release-version/releases/download/v1.0.24/jx-release-version_1.0.24_linux_amd64.tar.gz
        tar zxvf jx-release-version*
        chmod +x jx-release-version

    - name: Find next release version
      run: |
        VERSION=$(./jx-release-version)
        echo ::set-env name=release_version::$VERSION

    - name: Log into Docker Hub
      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u danielinclouds --password-stdin
    
    - name: Build the Docker image
      run: |
        docker build -t danielinclouds/semver-play-1:${release_version} . --build-arg=PORT=8080
      
    - name: Push Docker image
      run: |
        docker push danielinclouds/semver-play-1:${release_version} 
    
    - name: Tag Repo
      run: |
        git tag "${release_version}"
        hub push --tags
