name: Go Push

on:
- push
- pull_request

jobs:

  build:
    if: github.event.pull_request.merged != true
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.14
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        go get -v -t -d ./...

    - name: Build
      run: go build -v -o app .

    - name: Test
      run: go test -v .

    - name: Log into Docker Hub
      run: |
        echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u danielinclouds --password-stdin
    
    - name: Build the Docker image
      run: |
        LONG_SHA=${{ github.sha }}
        SHORT_SHA="${LONG_SHA:0:7}"
        docker build -t danielinclouds/semver-play-1:${SHORT_SHA} . --build-arg=PORT=8080
      
    - name: Push Docker image
      run: |
        LONG_SHA=${{ github.sha }}
        SHORT_SHA="${LONG_SHA:0:7}"
        docker push danielinclouds/semver-play-1:${SHORT_SHA} 
