name: Go Push

on:
- push
# - pull_request

jobs:

  build:
    name: Testing
    runs-on: ubuntu-latest
    steps:

    - name: Print event
      run: |
        echo ${{ github.event }}
    
    - name: Step 1
      run: |
        echo " Step 1"

    - name: Step 2
      run: |
        echo " Step 2"

    - name: Step 3
      run: |
        echo " Step 3"
